#pragma once

#include "NativeGameplayTags.h"

namespace BaseGameplayTag
{
	//Input Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Walk);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Prone);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Turn);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Punch);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interaction);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LeftLeaning);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_RightLeaning);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_CameraTransition);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_RightShouldering);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LeftShouldering);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_PrimaryWeapon);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SecondaryWeapon);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_PistolWeapon);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MeleeWeapon);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ThrowableWeapon);
	
	// Airplane Input Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Airplane_Look);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Airplane_Fall);

	// Inventory Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle_Inventory);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle_WorldMap);

	// Weapon Input Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Equip);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_UnEquip);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Fire);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Reload);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_ChangeFireMode);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Zoom);

	// Vehicle Input Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Vehicle_Break);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Vehicle_Steering);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Vehicle_Throttle);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Vehicle_HandBreak);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Vehicle_VehicleLook);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Vehicle_GetOut);
	
	// Weapon Action Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_Fire);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_Reload);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_ChangeFireMode);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_Zoom);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_UseItem);

	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Pickup);


	
	// Weapon Equip
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_Equip);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_UnEquip);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_Primary);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_Secondary);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_Pistol);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_Melee);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_Throwable);
	

	// Weapon Event Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Action_Equip);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Action_UnEquip);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Action_Reload);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Action_ReloadEnd);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Action_HideMag);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Action_VisibleMag);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Action_CompleteUseItem);

	// Hit Event Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Action_Hit);
	
	//Weapon Type Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Rifle);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Melee);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Grenade);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Unarmed);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Gun_AR);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Gun_Pistol);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Gun_SR);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Gun_SG);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Gun_DMR);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Gun_SMG);
	
	
	
	
	
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Prone);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Stand);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Crouch);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Dead);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Turn);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Swim);
	
	// Data Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_HealthRegen);

	
}